- hosts: name_node
  vars: 
     - shared_folder: "nn11" 
  tasks:
     - copy: 
        src: "/root/hadoop-1.2.1-1.x86_64.rpm"
        dest: "/root/"

     - copy: 
        src: "/root/jdk-8u171-linux-x64.rpm"
        dest: "/root/"
      
     - name: "checking JDK installed or not"
       command: "rpm -q jdk1.8"
       register: java
       ignore_errors: yes
       
     - name: "Installing Jdk..."
       command: "yum install jdk-8u171-linux-x64.rpm -y"
       when: java.rc !=0

     - name: "checking hadoop installed or not"
       command: "rpm -q hadoop"
       register: hadoop       
       ignore_errors: yes

     - name: "Installing Hadoop..."
       command: "rpm -i hadoop-1.2.1-1.x86_64.rpm --force"        
       when: hadoop.rc !=0

     - name: "Configuring hdfs-site.xml file..."
       template:
        src: "/workspace/ansible/nn_hdfs.xml"
        dest: "/etc/hadoop/hdfs-site.xml"

     - name: "Configuring core-site.xml file..."
       template:        
        src: "/workspace/ansible/core.xml"
        dest: "/etc/hadoop/core-site.xml"

     - file: 
        path: "{{ shared_folder }}"
        state: directory
     
     - name: "formatting the NN shared folder"
       shell: " hadoop namenode -format -force"

     - name: "startig the NameNode"
       command: "hadoop-daemon.sh start namenode"
  
     - name: "Stopping Firewall"
       command: "systemctl stop firewalld"

- hosts: data_node
  vars: 
     - dn_shared_folder: "dn11"
  tasks:
     - copy: 
        src: "/root/hadoop-1.2.1-1.x86_64.rpm"
        dest: "/root/"

     - copy: 
        src: "/root/jdk-8u171-linux-x64.rpm"
        dest: "/root/"
      
     - name: "checking java installed or not"
       command: "rpm -q jdk1.8"
       register: java
       ignore_errors: yes

     - name: "Installing Java..."
       command: "yum install jdk-8u171-linux-x64.rpm -y"        
       when: java.rc !=0

     - name: "checking hadoop installed or not"
       command: "rpm -q hadoop"
       register: hadoop
       ignore_errors: yes
     
     - name: "Installing Hadoop..."
       command: "rpm -i hadoop-1.2.1-1.x86_64.rpm --force"
       when: hadoop.rc !=0

     - name: "Configuring hdfs-site.xml file..."
       template:
        src: "/workspace/ansible/dn_hdfs.xml"
        dest: "/etc/hadoop/hdfs-site.xml"

     - name: "Configuring core-site.xml file..."
       template:        
        src: "/workspace/ansible/core.xml"
        dest: "/etc/hadoop/core-site.xml"

     - file: 
        path: "{{ dn_shared_folder }}"
        state: directory

     - name: "startig the DataNode"
       command: "hadoop-daemon.sh start datanode"

        
          
        
